name: findet
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17
  go_router: ^14.6.3
  intl: ^0.19.0
  fluttertoast: ^8.2.10
  flutter_bloc: ^9.0.0
  syncfusion_flutter_charts: ^28.2.6
  logger: ^2.5.0
  injectable: ^2.5.0
  dotted_border: ^2.1.0
  cloud_firestore: ^5.6.5
  firebase_core: ^3.12.1
  dropdown_button2: ^2.3.9
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  fonts:
  - family: Inter
    fonts:
      - asset: lib/assets/fonts/Inter-Bold.ttf
        weight: 700
      - asset: lib/assets/fonts/Inter-SemiBold.ttf
        weight: 600
      - asset: lib/assets/fonts/Inter-Medium.ttf
        weight: 500
      - asset: lib/assets/fonts/Inter-Regular.ttf
        weight: 400
  generate: true
  uses-material-design: true
  assets:
    - lib/assets/images/icons/tabs/
    - lib/assets/images/icons/emotions/
    - lib/assets/images/icons/additionals/
    - lib/assets/images/quotes/
    - lib/assets/images/app/
flutter_intl:
  enabled: true
